#!/usr/bin/env python3
"""Generate src-tauri/addresses/40204.json, the address book this app embeds.

Source of truth: citrate-chain/contracts/addresses/40204.json (the canonical book
the reroll ceremony regenerates). A reroll moves these addresses, so the app's
copy is GENERATED from that book, never hand-edited.

Fail-closed checks, all before anything is written:
  * every address the app needs is present and is 0x + 40 hex;
  * no two app pins share an address;
  * with --rpc, every pinned address has CODE on the live chain, the chain id
    matches, and block 0 hashes to --genesis (so the book and the chain the app
    will talk to are the same chain).

Usage:
  scripts/sync-addresses.py --book ../citrate-chain/contracts/addresses/40204.json \
      --genesis 0x<64 hex> --rpc https://rpc.citrate.ai
"""
import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "src-tauri" / "addresses" / "40204.json"
CHAIN_ID = 40204
MARKER = (
    "GENERATED by scripts/sync-addresses.py from citrate-chain/contracts/addresses/"
    "40204.json. Do not hand-edit — a reroll moves these, and a hand-edit is how they drift."
)

# Every contract this app reads. REQUIRED names must exist in the book and have
# code; the app cannot do its job without them.
REQUIRED = [
    "CitrateMemberSBT",
    "MembershipStakeVault",
    "ValidatorRegistry",
    "CitrateWalletFactory",
    "LiquidStakingPool",
    "CitratePaymaster",
    "IPFSIncentivesV3",
    "ModelRegistry",
    "SkillRegistry",
]
# OPTIONAL names are emitted only when the book carries them (the cooperative
# contracts deploy from a separate repo). The app treats an absent one as
# "unavailable", never as a guessed address.
OPTIONAL = ["PatronageLedger", "ModelCooperative"]

ADDR = re.compile(r"^0x[0-9a-fA-F]{40}$")
HASH = re.compile(r"^0x[0-9a-fA-F]{64}$")


def die(msg: str) -> None:
    print(f"sync-addresses: ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def flatten(book: dict) -> dict:
    """Collect name -> address from every section of the canonical book."""
    out = {}
    for section in ("contracts", "aaStack", "planned"):
        for name, addr in (book.get(section) or {}).items():
            if isinstance(addr, str) and ADDR.match(addr):
                out.setdefault(name, addr)
    return out


def rpc(url: str, method: str, params: list):
    req = urllib.request.Request(
        url,
        data=json.dumps({"jsonrpc": "2.0", "id": 1, "method": method, "params": params}).encode(),
        headers={"content-type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=20) as r:
        body = json.load(r)
    if "error" in body:
        die(f"{method} failed: {body['error']}")
    return body["result"]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--book", required=True, help="citrate-chain contracts/addresses/40204.json")
    ap.add_argument("--genesis", required=True, help="block-0 hash of the chain this build targets")
    ap.add_argument("--rpc", help="live RPC to verify chain id, genesis and code at every pin")
    ap.add_argument("--check", action="store_true", help="verify only; do not write")
    a = ap.parse_args()

    if not HASH.match(a.genesis):
        die(f"--genesis must be 0x + 64 hex, got {a.genesis!r}")
    genesis = a.genesis.lower()

    book = json.loads(Path(a.book).read_text())
    if int(book.get("chainId", 0)) != CHAIN_ID:
        die(f"book chainId {book.get('chainId')} != {CHAIN_ID}")
    flat = flatten(book)

    pins = {}
    for name in REQUIRED:
        if name not in flat:
            die(f"{name} is missing from {a.book}")
        pins[name] = flat[name]
    for name in OPTIONAL:
        if name in flat:
            pins[name] = flat[name]

    seen = {}
    for name, addr in pins.items():
        low = addr.lower()
        if low in seen:
            die(f"{name} and {seen[low]} share address {addr}")
        seen[low] = name

    if a.rpc:
        cid = int(rpc(a.rpc, "eth_chainId", []), 16)
        if cid != CHAIN_ID:
            die(f"{a.rpc} is chain {cid}, not {CHAIN_ID}")
        g = (rpc(a.rpc, "eth_getBlockByNumber", ["0x0", False]) or {}).get("hash", "").lower()
        if g != genesis:
            die(f"{a.rpc} genesis {g} != --genesis {genesis}: the book and the live chain disagree")
        missing = [n for n, ad in pins.items() if rpc(a.rpc, "eth_getCode", [ad, "latest"]) in (None, "0x", "0x0")]
        if missing:
            die("no code on the live chain at: " + ", ".join(f"{n} {pins[n]}" for n in missing))

    out = {"_comment": MARKER, "chainId": CHAIN_ID, "genesisHash": genesis, "addresses": pins}
    if a.check:
        print(f"sync-addresses: OK ({len(pins)} pins{', verified live' if a.rpc else ''})")
        return
    OUT.write_text(json.dumps(out, indent=2) + "\n")
    print(f"sync-addresses: wrote {OUT.relative_to(REPO)} ({len(pins)} pins{', verified live' if a.rpc else ''})")


if __name__ == "__main__":
    main()
